package com.osproject.shell.client.components;

import com.osproject.shell.client.core.PerformanceGraphics;
import com.osproject.shell.client.core.ProcessesTable;
import com.osproject.shell.client.core.Shell;
import com.osproject.shell.client.utils.InterfaceColors;
import java.awt.BorderLayout;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JTable;
import javax.swing.plaf.basic.BasicScrollBarUI;
import javax.swing.text.BadLocationException;
import javax.swing.text.html.HTMLDocument;
import org.jfree.chart.ChartPanel;

public class MainFrame extends javax.swing.JFrame {

    private final LoginFrame loginFrame;
    private final PerformanceGraphics performanceGraphics;
    private HTMLDocument doc;
    private final Shell shell;

    private int xMouse;
    private int yMouse;
    private final ImageIcon icon = new ImageIcon("C:\\Users\\ksmar\\OneDrive\\Documentos\\NetBeansProjects\\shell-client\\src\\main\\java\\com\\osproject\\shell\\client\\images\\play.png");
    private final ImageIcon iconSelected = new ImageIcon("C:\\Users\\ksmar\\OneDrive\\Documentos\\NetBeansProjects\\shell-client\\src\\main\\java\\com\\osproject\\shell\\client\\images\\play_select.png");

    /**
     * Creates new form MainFrame
     *
     */
    public MainFrame(LoginFrame loginFrame) {
        this.loginFrame = loginFrame;
        this.shell = new Shell(this.loginFrame);
        this.performanceGraphics = new PerformanceGraphics(this, this.loginFrame);
        if (this.loginFrame.getLogin().isLogin()) {

            this.setUndecorated(true);

            initComponents();

            jScrollPane1.getVerticalScrollBar().setUI(new BasicScrollBarUI() {
                @Override
                protected void configureScrollBarColors() {
                    this.thumbColor = InterfaceColors.BLUE;
                }
            });

            this.setLocationRelativeTo(null);

            ChartPanel driveChartPanel = performanceGraphics.createPanelDrive();
            ChartPanel procecesorChartPanel = performanceGraphics.createPanelProccesor();
            ChartPanel ramChartPanel = performanceGraphics.createPanelRam();

            driveChartPanel.setPopupMenu(null);
            driveChartPanel.setDomainZoomable(false);
            driveChartPanel.setRangeZoomable(false);

            procecesorChartPanel.setPopupMenu(null);
            procecesorChartPanel.setDomainZoomable(false);
            procecesorChartPanel.setRangeZoomable(false);

            ramChartPanel.setPopupMenu(null);
            ramChartPanel.setDomainZoomable(false);
            ramChartPanel.setRangeZoomable(false);

            this.drivePanel.add(driveChartPanel, BorderLayout.CENTER);
            this.processorPanel.add(procecesorChartPanel, BorderLayout.CENTER);
            this.ramPanel.add(ramChartPanel, BorderLayout.CENTER);

            doc = (HTMLDocument) consoleArea.getDocument();
            this.processesTable.getTableHeader().setBackground(InterfaceColors.BLUE);
            new ProcessesTable(this, this.loginFrame).createProcessesTable();

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPane = new javax.swing.JPanel();
        headBar = new javax.swing.JPanel();
        btnMin = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnClose = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        sidePane = new javax.swing.JPanel();
        titlePane = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        titleLabel1 = new javax.swing.JLabel();
        optionOne = new javax.swing.JPanel();
        shellLabel = new javax.swing.JLabel();
        optionTwo = new javax.swing.JPanel();
        performanceLabel = new javax.swing.JLabel();
        optionThree = new javax.swing.JPanel();
        processesLabel = new javax.swing.JLabel();
        sectionPane = new javax.swing.JPanel();
        sectionLabel = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        homePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        shellPanel = new javax.swing.JPanel();
        txtComand = new javax.swing.JTextField();
        btnExecute = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        consoleArea = new javax.swing.JTextPane();
        executeIcon = new javax.swing.JLabel();
        performancePanel = new javax.swing.JPanel();
        processorPanel = new javax.swing.JPanel();
        ramPanel = new javax.swing.JPanel();
        drivePanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ramPercent = new javax.swing.JLabel();
        drivePercent = new javax.swing.JLabel();
        processorPercent = new javax.swing.JLabel();
        processesPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        processesTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contentPane.setBackground(new java.awt.Color(255, 255, 255));
        contentPane.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        contentPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headBar.setOpaque(false);
        headBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headBarMouseDragged(evt);
            }
        });
        headBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headBarMousePressed(evt);
            }
        });
        headBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMin.setBackground(new java.awt.Color(9, 121, 176));
        btnMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinMouseExited(evt);
            }
        });
        btnMin.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("-");
        btnMin.add(jLabel4, java.awt.BorderLayout.CENTER);

        headBar.add(btnMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 0, 40, 20));

        btnClose.setBackground(new java.awt.Color(9, 121, 176));
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseMouseExited(evt);
            }
        });
        btnClose.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        btnClose.add(jLabel2, java.awt.BorderLayout.CENTER);

        headBar.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 0, 40, 20));

        contentPane.add(headBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 20));

        sidePane.setBackground(new java.awt.Color(0, 65, 115));
        sidePane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titlePane.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        titlePane.setOpaque(false);
        titlePane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                titlePaneMouseClicked(evt);
            }
        });
        titlePane.setLayout(new java.awt.GridLayout(0, 1));

        titleLabel.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Sistema Shell");
        titleLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        titleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titleLabel.setPreferredSize(new java.awt.Dimension(100, 29));
        titlePane.add(titleLabel);

        titleLabel1.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        titleLabel1.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel1.setText("Windows - Linux");
        titleLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        titleLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titleLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        titlePane.add(titleLabel1);

        sidePane.add(titlePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 110));

        optionOne.setBackground(new java.awt.Color(22, 75, 115));
        optionOne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optionOneMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                optionOneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                optionOneMouseExited(evt);
            }
        });
        optionOne.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        shellLabel.setBackground(new java.awt.Color(0, 65, 115));
        shellLabel.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        shellLabel.setForeground(new java.awt.Color(255, 255, 255));
        shellLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        shellLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\ksmar\\OneDrive\\Documentos\\NetBeansProjects\\shell-client\\src\\main\\java\\com\\osproject\\shell\\client\\images\\console.png")); // NOI18N
        shellLabel.setText("Shell");
        shellLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        optionOne.add(shellLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 200, 60));

        sidePane.add(optionOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 220, -1));

        optionTwo.setBackground(new java.awt.Color(22, 75, 115));
        optionTwo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        optionTwo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optionTwoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                optionTwoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                optionTwoMouseExited(evt);
            }
        });
        optionTwo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        performanceLabel.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        performanceLabel.setForeground(new java.awt.Color(255, 255, 255));
        performanceLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        performanceLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\ksmar\\OneDrive\\Documentos\\NetBeansProjects\\shell-client\\src\\main\\java\\com\\osproject\\shell\\client\\images\\dashboard.png")); // NOI18N
        performanceLabel.setText("Rendimiento");
        optionTwo.add(performanceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 200, 60));

        sidePane.add(optionTwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 220, 58));

        optionThree.setBackground(new java.awt.Color(22, 75, 115));
        optionThree.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        optionThree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optionThreeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                optionThreeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                optionThreeMouseExited(evt);
            }
        });
        optionThree.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        processesLabel.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        processesLabel.setForeground(new java.awt.Color(255, 255, 255));
        processesLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        processesLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\ksmar\\OneDrive\\Documentos\\NetBeansProjects\\shell-client\\src\\main\\java\\com\\osproject\\shell\\client\\images\\linux-client.png")); // NOI18N
        processesLabel.setText("Procesos");
        optionThree.add(processesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 200, 60));

        sidePane.add(optionThree, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 220, 58));

        contentPane.add(sidePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 550));

        sectionPane.setBackground(new java.awt.Color(9, 121, 176));

        sectionLabel.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        sectionLabel.setForeground(new java.awt.Color(255, 255, 255));
        sectionLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sectionLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\ksmar\\OneDrive\\Documentos\\NetBeansProjects\\shell-client\\src\\main\\java\\com\\osproject\\shell\\client\\images\\home.png")); // NOI18N
        sectionLabel.setText("Home");

        javax.swing.GroupLayout sectionPaneLayout = new javax.swing.GroupLayout(sectionPane);
        sectionPane.setLayout(sectionPaneLayout);
        sectionPaneLayout.setHorizontalGroup(
            sectionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sectionPaneLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(sectionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(511, Short.MAX_VALUE))
        );
        sectionPaneLayout.setVerticalGroup(
            sectionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sectionPaneLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(sectionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        contentPane.add(sectionPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 0, 940, 80));

        homePanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 65, 115));
        jLabel1.setText("¡Bienvenido de vuelta!");

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Este es el Sistema Shell Windows-Linux, con el que puedes:");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("- Monitorear el estado de consumo de tu sistema linux.");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("- Ejecutar comandos en tu sistema linux.");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Para esto solo has click en las opciones que tienes en la barra lateral.");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel11.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(9, 121, 176));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("¡Esperamos que sea util para ti!");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel12.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("- Ver los procesos que se están ejecutando.");
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel3.setText("© 2021 Sistema Shell Windows Linux - Proyecto Sistemas Operativos");

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel5.setText("Kevin Santiago Martinez - Joshep Mateo Granda");

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(homePanelLayout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(homePanelLayout.createSequentialGroup()
                                .addGap(335, 335, 335)
                                .addComponent(jLabel5)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 853, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(271, 271, 271))))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addGap(15, 15, 15)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(24, 24, 24)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(20, 20, 20))
        );

        jTabbedPane1.addTab("Home", homePanel);

        shellPanel.setBackground(new java.awt.Color(255, 255, 255));
        shellPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtComand.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtComand.setForeground(new java.awt.Color(204, 204, 204));
        txtComand.setText("Introduce un comando");
        txtComand.setBorder(null);
        txtComand.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtComandFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtComandFocusLost(evt);
            }
        });
        txtComand.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtComandMousePressed(evt);
            }
        });
        txtComand.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtComandKeyPressed(evt);
            }
        });
        shellPanel.add(txtComand, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 830, 50));

        btnExecute.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExecute.setOpaque(false);
        btnExecute.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExecuteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExecuteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExecuteMouseExited(evt);
            }
        });
        btnExecute.setLayout(new java.awt.BorderLayout());
        shellPanel.add(btnExecute, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 60, 50));

        jPanel1.setBackground(new java.awt.Color(9, 121, 176));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        shellPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 830, 2));
        jPanel1.getAccessibleContext().setAccessibleName("");

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N

        consoleArea.setEditable(false);
        consoleArea.setBackground(new java.awt.Color(255, 255, 255));
        consoleArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(9, 121, 176)));
        consoleArea.setContentType("text/html"); // NOI18N
        consoleArea.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        consoleArea.setFocusable(false);
        jScrollPane1.setViewportView(consoleArea);

        shellPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 98, 890, 360));

        executeIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        executeIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\ksmar\\OneDrive\\Documentos\\NetBeansProjects\\shell-client\\src\\main\\java\\com\\osproject\\shell\\client\\images\\play.png")); // NOI18N
        shellPanel.add(executeIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 20, 60, -1));

        jTabbedPane1.addTab("Shell", shellPanel);

        performancePanel.setBackground(new java.awt.Color(255, 255, 255));
        performancePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        processorPanel.setLayout(new java.awt.BorderLayout());
        performancePanel.add(processorPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 520, 170));

        ramPanel.setLayout(new java.awt.BorderLayout());
        performancePanel.add(ramPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 520, 170));

        drivePanel.setLayout(new java.awt.BorderLayout());
        performancePanel.add(drivePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, 290, 280));

        jLabel13.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel13.setText("Ram:");
        performancePanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 242, 109, 30));

        jLabel14.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel14.setText("Disco:");
        performancePanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, 130, 30));

        jLabel15.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel15.setText("Procesador:");
        performancePanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 109, 30));

        ramPercent.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        ramPercent.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ramPercent.setText("100%");
        performancePanel.add(ramPercent, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 40, -1));

        drivePercent.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        drivePercent.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        drivePercent.setText("100%");
        performancePanel.add(drivePercent, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 80, 40, -1));

        processorPercent.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        processorPercent.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        processorPercent.setText("100%");
        performancePanel.add(processorPercent, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 40, -1));

        jTabbedPane1.addTab("Performance", performancePanel);

        processesPanel.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(9, 121, 176)));

        processesTable.setAutoCreateRowSorter(true);
        processesTable.setBackground(new java.awt.Color(255, 255, 255));
        processesTable.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        processesTable.setForeground(new java.awt.Color(0, 0, 0));
        processesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        processesTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        processesTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        processesTable.setGridColor(new java.awt.Color(255, 255, 255));
        processesTable.setRowSelectionAllowed(false);
        processesTable.setShowGrid(false);
        processesTable.getTableHeader().setResizingAllowed(false);
        processesTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(processesTable);

        javax.swing.GroupLayout processesPanelLayout = new javax.swing.GroupLayout(processesPanel);
        processesPanel.setLayout(processesPanelLayout);
        processesPanelLayout.setHorizontalGroup(
            processesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(processesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 918, Short.MAX_VALUE)
                .addContainerGap())
        );
        processesPanelLayout.setVerticalGroup(
            processesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, processesPanelLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("ProcessesPane", processesPanel);

        contentPane.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 930, 510));

        getContentPane().add(contentPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseEntered
        btnClose.setBackground(InterfaceColors.RED);
    }//GEN-LAST:event_btnCloseMouseEntered

    private void btnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
        btnClose.setBackground(InterfaceColors.BLUE);
    }//GEN-LAST:event_btnCloseMouseExited

    private void btnMinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinMouseEntered
        btnMin.setBackground(InterfaceColors.DARK_BLUE);
    }//GEN-LAST:event_btnMinMouseEntered

    private void btnMinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinMouseExited
        btnMin.setBackground(InterfaceColors.BLUE);
    }//GEN-LAST:event_btnMinMouseExited

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        try {
            this.loginFrame.getDataOutputStream().writeUTF("0");
            this.loginFrame.getSocket().close();
            this.loginFrame.getDataOutputStream().close();
            this.loginFrame.getDataInputStream().close();
            System.exit(0);
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.exit(0);
    }//GEN-LAST:event_btnCloseMouseClicked

    private void headBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headBarMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headBarMousePressed

    private void headBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headBarMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headBarMouseDragged

    private void btnMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btnMinMouseClicked

    private void titlePaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titlePaneMouseClicked
        sectionLabel.setText("Home");
        ImageIcon ico = new ImageIcon("C:\\Users\\ksmar\\OneDrive\\Documentos\\NetBeansProjects\\shell-client\\src\\main\\java\\com\\osproject\\shell\\client\\images\\home.png");
        sectionLabel.setIcon(ico);
        optionOne.setBackground(InterfaceColors.BLUE_OPTION);
        optionTwo.setBackground(InterfaceColors.BLUE_OPTION);
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_titlePaneMouseClicked

    private void optionOneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optionOneMouseEntered
        optionOne.setBackground(InterfaceColors.BLUE);
    }//GEN-LAST:event_optionOneMouseEntered

    private void optionOneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optionOneMouseExited
        if (jTabbedPane1.getSelectedIndex() != 1) {
            optionOne.setBackground(InterfaceColors.BLUE_OPTION);
        }
    }//GEN-LAST:event_optionOneMouseExited

    private void optionTwoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optionTwoMouseEntered
        optionTwo.setBackground(InterfaceColors.BLUE);
    }//GEN-LAST:event_optionTwoMouseEntered

    private void optionTwoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optionTwoMouseExited
        if (jTabbedPane1.getSelectedIndex() != 2) {
            optionTwo.setBackground(InterfaceColors.BLUE_OPTION);
        }
    }//GEN-LAST:event_optionTwoMouseExited

    private void optionOneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optionOneMouseClicked
        sectionLabel.setText("Shell");
        ImageIcon ico = new ImageIcon("C:\\Users\\ksmar\\OneDrive\\Documentos\\NetBeansProjects\\shell-client\\src\\main\\java\\com\\osproject\\shell\\client\\images\\console.png");
        sectionLabel.setIcon(ico);
        optionTwo.setBackground(InterfaceColors.BLUE_OPTION);
        optionThree.setBackground(InterfaceColors.BLUE_OPTION);
        optionOne.setBackground(InterfaceColors.BLUE);
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_optionOneMouseClicked

    private void optionTwoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optionTwoMouseClicked
        txtComand.setText("Introduce un comando");
        txtComand.setForeground(InterfaceColors.GRAY);
        sectionLabel.setText("Rendimiento");
        ImageIcon ico = new ImageIcon("C:\\Users\\ksmar\\OneDrive\\Documentos\\NetBeansProjects\\shell-client\\src\\main\\java\\com\\osproject\\shell\\client\\images\\dashboard.png");
        sectionLabel.setIcon(ico);
        optionOne.setBackground(InterfaceColors.BLUE_OPTION);
        optionThree.setBackground(InterfaceColors.BLUE_OPTION);
        optionTwo.setBackground(InterfaceColors.BLUE);
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_optionTwoMouseClicked

    private void txtComandKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtComandKeyPressed
        if (txtComand.getText().equals("Introduce un comando")) {
            txtComand.setText("");
            txtComand.setForeground(InterfaceColors.BLACK);
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            commandExecute();
        }
    }//GEN-LAST:event_txtComandKeyPressed

    private void txtComandMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtComandMousePressed
        if (txtComand.getText().equals("Introduce un comando")) {
            txtComand.setText("");
            txtComand.setForeground(InterfaceColors.BLACK);
        }
    }//GEN-LAST:event_txtComandMousePressed

    private void txtComandFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtComandFocusLost
        if (txtComand.getText().isBlank()) {
            txtComand.setText("Introduce un comando");
            txtComand.setForeground(InterfaceColors.GRAY);
        }
    }//GEN-LAST:event_txtComandFocusLost

    private void btnExecuteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExecuteMouseClicked
        commandExecute();
    }//GEN-LAST:event_btnExecuteMouseClicked

    private void btnExecuteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExecuteMouseEntered
        executeIcon.setIcon(iconSelected);
    }//GEN-LAST:event_btnExecuteMouseEntered

    private void btnExecuteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExecuteMouseExited
        executeIcon.setIcon(icon);
    }//GEN-LAST:event_btnExecuteMouseExited

    private void txtComandFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtComandFocusGained
        if (txtComand.getText().equals("Introduce un comando")) {
            txtComand.setText("");
            txtComand.setForeground(InterfaceColors.BLACK);
        }
    }//GEN-LAST:event_txtComandFocusGained

    private void optionThreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optionThreeMouseClicked
        sectionLabel.setText("Processes");
        ImageIcon ico = new ImageIcon("C:\\Users\\ksmar\\OneDrive\\Documentos\\NetBeansProjects\\shell-client\\src\\main\\java\\com\\osproject\\shell\\client\\images\\linux-client.png");
        sectionLabel.setIcon(ico);
        optionOne.setBackground(InterfaceColors.BLUE_OPTION);
        optionTwo.setBackground(InterfaceColors.BLUE_OPTION);
        optionThree.setBackground(InterfaceColors.BLUE);
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_optionThreeMouseClicked

    private void optionThreeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optionThreeMouseEntered
        optionThree.setBackground(InterfaceColors.BLUE);
    }//GEN-LAST:event_optionThreeMouseEntered

    private void optionThreeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optionThreeMouseExited
        if (jTabbedPane1.getSelectedIndex() != 3) {
            optionThree.setBackground(InterfaceColors.BLUE_OPTION);
        }
    }//GEN-LAST:event_optionThreeMouseExited

    public void setDrivePercent(String percent) {
        drivePercent.setText(percent);
    }

    public void setProcessorPercent(String percent) {
        processorPercent.setText(percent);
    }

    public void setRamPercent(String percent) {
        ramPercent.setText(percent);
    }

    public JTable getProcessesTable() {
        return processesTable;
    }

    private void commandExecute() {
        if (!txtComand.getText().isBlank() && !txtComand.getText().equals("Introduce un comando")) {
            if (txtComand.getText().equals("clr") || txtComand.getText().equals("clear")) {
                consoleArea.setText("");
                txtComand.setText("");
                txtComand.setForeground(InterfaceColors.BLACK);
            } else {
                btnExecute.requestFocusInWindow();

                String[] data = shell.executeCommand(txtComand.getText()).split(":///:");

                String text = "<font color='#0979B0' face='roboto'>client@windows~$ </font>"
                        + "<font color='#999999' face='roboto'>" + txtComand.getText() + "</font><br>"
                        + "<font color='#004173' face='roboto'>server@linux~$ </font>";

                if (!(data.length > 0)) {
                    text += "<br>";
                }

                for (String line : data) {
                    text += "<font color='#000000' face='roboto'>" + line + "</font><br>";
                }

                try {
                    doc.insertAfterEnd(doc.getCharacterElement(doc.getLength()), text);
                } catch (BadLocationException | IOException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }

                txtComand.setText("Introduce un comando");
                txtComand.setForeground(InterfaceColors.GRAY);
                txtComand.requestFocusInWindow();
            }
        } else {
            loginFrame.getAlert().getTitleLabel().setText("¡Atención!");
            loginFrame.getAlert().getMessageLabel().setText("Por favor introduzca un comando");
            loginFrame.getAlert().setVisible(true);
            txtComand.requestFocusInWindow();
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnClose;
    private javax.swing.JPanel btnExecute;
    private javax.swing.JPanel btnMin;
    private javax.swing.JTextPane consoleArea;
    private javax.swing.JPanel contentPane;
    private javax.swing.JPanel drivePanel;
    private javax.swing.JLabel drivePercent;
    private javax.swing.JLabel executeIcon;
    private javax.swing.JPanel headBar;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel optionOne;
    private javax.swing.JPanel optionThree;
    private javax.swing.JPanel optionTwo;
    private javax.swing.JLabel performanceLabel;
    private javax.swing.JPanel performancePanel;
    private javax.swing.JLabel processesLabel;
    private javax.swing.JPanel processesPanel;
    private javax.swing.JTable processesTable;
    private javax.swing.JPanel processorPanel;
    private javax.swing.JLabel processorPercent;
    private javax.swing.JPanel ramPanel;
    private javax.swing.JLabel ramPercent;
    private javax.swing.JLabel sectionLabel;
    private javax.swing.JPanel sectionPane;
    private javax.swing.JLabel shellLabel;
    private javax.swing.JPanel shellPanel;
    private javax.swing.JPanel sidePane;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel titleLabel1;
    private javax.swing.JPanel titlePane;
    private javax.swing.JTextField txtComand;
    // End of variables declaration//GEN-END:variables

}
